### PR TITLE
Add a Heroku Button

### PR DESCRIPTION
**Pull request by freeformz**
For this to 100% the app.json would also need to be up to date and correct. I haven't verified that though.

### CODE REVIEW

**Comment by flexd** [comment]
The deploy button is just magic that relies on app.json? I'll have to read about it, I think app.json is missing some environment variables.

**Comment by freeformz** [comment]
@flexd Essentially, yes. [This](https://devcenter.heroku.com/articles/app-json-schema) is the published schema. And [this](https://devcenter.heroku.com/articles/heroku-button) is the button docs.

**Comment by flexd** [comment]
Nice! I was actually looking at this a few hours before you merged it. I was going to see if app.json was up to date and correct, but then forgot/ran out of time. :)

**Comment by freeformz** [comment]
@flexd it should be. If not we can fix it. ;-)

**Pull request merged**
