### PR TITLE
Add Slack SVG badge.

### PR DESCRIPTION
**Pull request by danielmai**
Slack SVG badge containing active and total user count is accessible via /badge.svg. Created with [go-badge](https://github.com/narqo/go-badge).

### CODE REVIEW

**Comment by flexd** [comment]
Looks good! 👍

**Comment by danielmai** [comment]
Oops, I didn't intend to include https://github.com/flexd/slackinviter/pull/26/commits/c9190a9665566ac29904539fd372e9c70a36ea84 in this PR. I made reCAPTCHA optional to make slackinviter usable for users where Google is blocked.

**Comment by flexd** [comment]
If you can split that into it's on PR we can merge them separately :-) I think someone asked for that at some point

**Comment by danielmai** [comment]
It's been separated now.

**Comment by flexd** [comment]
Live at https://invite.slack.golangbridge.org/badge.svg 👍

**Pull request merged**
